### ISSUE TITLE
[Feature Request] Option to show a smaller list of letters.

### ISSUE THREAD

**Issue by Luukxt8** [peternijssen/lovelace-postnl#10]
Is it possible to give us the option to choose how big the list of letters is in the card. Because im getting a list of 15 letters.  Way to much information , and 95% are already delivered. But still showing because of the unreliable postNL letter status.
A maximum of 5 letters would be enough for me.

Also i would like the option to see the last letter as an image in the lovelace card. See the images and link below as a reference :)
![image](https://user-images.githubusercontent.com/50046608/56848962-a6b69700-68ee-11e9-994c-f25fe89b188b.png)

![image](https://user-images.githubusercontent.com/50046608/56848967-b3d38600-68ee-11e9-8115-19c77bca35d5.png)

https://community.home-assistant.io/t/usps-fedex-ups-custom-ui-card-lovelace-updated-11-27/79648

Please see the above as suggestions. I'm very happy with the new component en lovelace support.

**Comment by peternijssen** [comment]
How about filtering the letters based on the expected delivery date? So let's see you received 8 letters last week, 1 yesterday and 1 today. I could only show the ones from yesterday and today for example. Or would you prefer a hard limit like for example "5"?

**Comment by Luukxt8** [comment]
Your suggestion sound much better and neater! 👍 Lets go for that.

**Comment by peternijssen** [comment]
I believe it's solved with this update:
https://community.home-assistant.io/t/lovelace-postnl/112433/66?u=ptnijssen
