### ISSUE TITLE
[Feature Request] Option to show delivered for only a configurable amout of day's

### ISSUE THREAD

**Issue by reharmsen** [peternijssen/lovelace-postnl#11]
It would be nice to have an option to only show delivered packages for a configurable amount of day's.  Currently you can only show all delivered packages or none. (as far as I understand)

I would like to have delivered packages shown for one day, to see whether a packages scheduled to arrive today has been delivered.

I would like to only have the most upper one shown (today), even when it is delivered.

without filtering
![afbeelding](https://user-images.githubusercontent.com/22921691/56946090-80307000-6b29-11e9-9676-c8681deaeddf.png)

with filtering
![afbeelding](https://user-images.githubusercontent.com/22921691/56946391-46ac3480-6b2a-11e9-972b-88acc1cb5c6d.png)

PS. Don't look at the second line, this is a return package which I already deleted from mijn.postnl.nl as it was wrongly shown.

**Comment by peternijssen** [comment]
Good suggestion. Will look into this!

**Comment by peternijssen** [comment]
I believe it's solved with this update:
https://community.home-assistant.io/t/lovelace-postnl/112433/66
