### ISSUE TITLE
Infinite loop for letters

### ISSUE THREAD

**Issue by Luukxt8** [peternijssen/lovelace-postnl#15]
Looks like we got an infinite loop :) I put the limit on 5 days. It keeps loading new entries with the same letter. See screenshot
![image](https://user-images.githubusercontent.com/50046608/57786844-8717cf00-7734-11e9-8cfe-a178babb04c8.png)

While typing this post it's already on 138 letters and still going!

My config: 
date_format: DD MMM YYYY
delivery: sensor.postnl_delivery
distribution: sensor.postnl_distribution
hide:
  delivered: true
  first_letter: false
  header: false
letters: sensor.postnl_letters
past_days: 5
time_format: 'HH:mm'
type: 'custom:postnl-card'

**Comment by peternijssen** [comment]
Solved in 0.9.4 I believe
