### ISSUE TITLE
Unable to activate the custom component

### ISSUE THREAD

**Issue by ramonvanbiljouw** [peternijssen/lovelace-postnl#7]
Hi,

I've looked and looked, but I can't find a way to activate the custom component. Could you help? Regards, Ramon

**Comment by peternijssen** [comment]
If you mean the python files, just store both within your config directory /custom_components/postnl/
Then restart your HA instance. You should now have a "sensor.postnl_letters" and "sensor.postnl_packages" available.

https://developers.home-assistant.io/docs/en/creating_component_loading.html

**Comment by ramonvanbiljouw** [comment]
Hi Peter, hoi 😊 
I did put those files in the folder you mention. But no sensors. I had the postnl component installed but deactivated that.

**Comment by peternijssen** [comment]
You can keep the same postnl configuration as it was before to activate it. I'll add that to the forum topic to avoid confusion.

Additionally, I made a change earlier that might help you. Make sure you have the latest files I've created :)

**Comment by ramonvanbiljouw** [comment]
Hi Peter, It still doesn't work, but I think I know what is wrong. Looking into the sensor component it says: REQUIREMENTS = ['postnlpy==0.2.2']. Something you developed and is not installed at my configuration: HA version 0.92 installed in Docker on a Synology DS216+II. Could that be the case?
Using just the sensor.postnl for both packages and letters shows the card, but with the number of the sensor from the original component. Do you require more feedback on this?

**Comment by peternijssen** [comment]
This is due to HA 0.92.
I added a manifest.json file to the gist, which you should add to the same directory. Then restart HA;
https://gist.github.com/peternijssen/155c9060923adbc08d0998bbd8ed44bf

**Comment by ramonvanbiljouw** [comment]
That was it! Component loads well, no error messages. The only thing is that the title of the letters is not as nice as I have seen on your screen dump. Take a look.
<img width="517" alt="image" src="https://user-images.githubusercontent.com/37939474/56846562-128a0700-68d1-11e9-9ae4-b52e2c01cb3a.png">

**Comment by peternijssen** [comment]
Do you mean the color of the icons? That's the only difference I see between our themes I believe.

In regards to the status column, apparently a letter can have an unknown status. Will fix that it says "unknown".

**Comment by ramonvanbiljouw** [comment]
The colours of the icons depends on my theme setting. I thought the ^ were misplaced. I've updated everything, but still the status is without any status... 😊 And there should be more space between the end of the image and the title:
<img width="572" alt="image" src="https://user-images.githubusercontent.com/37939474/56853512-61fc2180-6929-11e9-9172-c5b3532f26ed.png">

**Comment by peternijssen** [comment]
The titles are just whatever PostNL decides. The status is unfortunately on some cases empty. It seems that PostNL is not consistent in this.

**Comment by peternijssen** [comment]
Added a bit more spacing below the image.
