### ISSUE TITLE
Letters can have an unknown status and not even an image

### ISSUE THREAD

**Issue by peternijssen** [peternijssen/lovelace-postnl#9]
Letters can have an unknown status, now resulting in an empty status. Let's put "unknown" over there.

Furthermore, a letter does not always have an image. If not, we shouldn't make the title a link to the not existing image.

**Comment by berthavekes2** [comment]
All the status of the letters stay on "unknown". Can this automatically change to "delivered" if it is past the delivery time??

![Schermopname (1)](https://user-images.githubusercontent.com/47527003/57037754-532eab00-6c58-11e9-9242-7f81d11842e6.png)
